### ISSUE TITLE
Disposed exception during playlist edit operation

### ISSUE THREAD

**Issue by peppy** [ppy/osu-server-spectator#114]
Opening for tracking purposes. Haven't figure out the cause yet..

```csharp
2022-03-27 14:16:58 [verbose]: [user:14613516] [room:162666] Editing playlist item 752460 for beatmap 1581930
2022-03-27 14:16:58 [verbose]: [user:27352453] [room:162666] User state changed from Ready to Idle
2022-03-27 14:16:58 [error]: [user:14613516] Failed to invoke hub method: EditPlaylistItem(osu.Game.Online.Rooms.MultiplayerPlaylistItem)
2022-03-27 14:16:58 [error]: System.ObjectDisposedException: Cannot access a disposed object.
2022-03-27 14:16:58 [error]: Object name: 'MultiplayerHub'.
2022-03-27 14:16:58 [error]: at Microsoft.AspNetCore.SignalR.Hub.CheckDisposed()
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.Hubs.MultiplayerHub.changeAndBroadcastUserState(ServerMultiplayerRoom room, MultiplayerRoomUser user, MultiplayerUserState state) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Hubs/MultiplayerHub.cs:line 739
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.Hubs.MultiplayerHub.unreadyAllUsers(ServerMultiplayerRoom room) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Hubs/MultiplayerHub.cs:line 982
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.Hubs.MultiplayerHub.OnPlaylistItemChanged(ServerMultiplayerRoom room, MultiplayerPlaylistItem item) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Hubs/MultiplayerHub.cs:line 939
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.Hubs.MultiplayerQueue.EditItem(MultiplayerPlaylistItem item, MultiplayerRoomUser user) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Hubs/MultiplayerQueue.cs:line 175
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.Hubs.MultiplayerHub.EditPlaylistItem(MultiplayerPlaylistItem item) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Hubs/MultiplayerHub.cs:line 500
2022-03-27 14:16:58 [error]: at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
2022-03-27 14:16:58 [error]: at osu.Server.Spectator.LoggingHubFilter.InvokeMethodAsync(HubInvocationContext invocationContext, Func`2 next) in /Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/LoggingHubFilter.cs:line 37
2022-03-27 14:16:59 [verbose]: [user:10872216] User disconnected
2022-03-27 14:16:59 [verbose]: [user:12176833] Connected
```

**Comment by smoogipoo** [comment]
Something very fishy is going on here. I've dug deep into SignalR internals + every method around `EditPlaylistItem` and I can't see how this is possible. Internally, the process is something like:
```
var hub = CreateHub();

if (anyFilters)
    await InvokeFilters(); // The last 'filter' is ExecuteMethod().
else
    await ExecuteMethod();

hub.Dispose();
```
So my instinct was to see if somehow `EditPlaylistItem()` is escaping the async context, if for example, `MultiplayerQueue.EditItem()` was a wrapped task that wasn't unwrapped. However this doesn't seem to be the case - all calls inside `EditPlaylistItem()` run to completion before the method itself returns.

Put another way, all tests pass with the following:
```diff
diff --git a/osu.Server.Spectator/Hubs/MultiplayerHub.cs b/osu.Server.Spectator/Hubs/MultiplayerHub.cs
index f35874d..671d399 100644
--- a/osu.Server.Spectator/Hubs/MultiplayerHub.cs
+++ b/osu.Server.Spectator/Hubs/MultiplayerHub.cs
@@ -935,6 +935,17 @@ namespace osu.Server.Spectator.Hubs
             if (item.ID == room.Settings.PlaylistItemId)
                 await unreadyAllUsers(room);

+            try
+            {
+                using (var roomUsage = await Rooms.GetForUse(room.RoomID))
+                {
+                    throw new InvalidOperationException();
+                }
+            }
+            catch
+            {
+            }
+
             await Clients.Group(GetGroupId(room.RoomID)).PlaylistItemChanged(item);
         }
```
At a bit of a loss right now.
